package deprecated.vistas;

/**
 *
 * @author jav
 */
public class Categorias_Ventas extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    public Categorias_Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Cat_Venta = new javax.swing.JLabel();
        jLab_Cod_Cat_Venta = new javax.swing.JLabel();
        jBut_Cancel_Ventas = new javax.swing.JButton();
        jBut_Guard_Ventas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_List_Cat_Ventas = new javax.swing.JTable();
        jBut_Buscar_Ventas = new javax.swing.JButton();
        jTxt_Cod_Cat_Venta = new javax.swing.JTextField();
        jComb_Cat_Ventas = new javax.swing.JComboBox<>();
        jBut_ed_Ventas = new javax.swing.JButton();
        jBut_Des_Ventas = new javax.swing.JButton();
        jLab_List_Cat_Venta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Cat_Venta.setText("Categoría Venta");
        getContentPane().add(jLab_Cat_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, -1, -1));

        jLab_Cod_Cat_Venta.setText("Código Categoría Venta");
        getContentPane().add(jLab_Cod_Cat_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 26, -1, -1));

        jBut_Cancel_Ventas.setText("Cancelar");
        getContentPane().add(jBut_Cancel_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 99, -1, -1));

        jBut_Guard_Ventas.setText("Guardar");
        jBut_Guard_Ventas.setToolTipText("");
        getContentPane().add(jBut_Guard_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 99, -1, -1));

        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 52, 22, -1));

        jTable_List_Cat_Ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código Categoría Venta", "Categoría Venta", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_List_Cat_Ventas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 216, 631, 159));

        jBut_Buscar_Ventas.setText("Buscar");
        getContentPane().add(jBut_Buscar_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 99, -1, -1));
        getContentPane().add(jTxt_Cod_Cat_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 23, 137, -1));

        jComb_Cat_Ventas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accesorios", "Bebestibles", "Comestibles" }));
        getContentPane().add(jComb_Cat_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 23, 141, -1));

        jBut_ed_Ventas.setText("Editar");
        getContentPane().add(jBut_ed_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 381, -1, -1));

        jBut_Des_Ventas.setText("Desactivar");
        jBut_Des_Ventas.setToolTipText("");
        jBut_Des_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_Des_VentasActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_Des_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 381, -1, -1));

        jLab_List_Cat_Venta.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLab_List_Cat_Venta.setText("Categoría de Venta");
        getContentPane().add(jLab_List_Cat_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 161, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_Des_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_Des_VentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBut_Des_VentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categorias_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categorias_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categorias_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categorias_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categorias_Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Buscar_Ventas;
    private javax.swing.JButton jBut_Cancel_Ventas;
    private javax.swing.JButton jBut_Des_Ventas;
    private javax.swing.JButton jBut_Guard_Ventas;
    private javax.swing.JButton jBut_ed_Ventas;
    private javax.swing.JComboBox<String> jComb_Cat_Ventas;
    private javax.swing.JLabel jLab_Cat_Venta;
    private javax.swing.JLabel jLab_Cod_Cat_Venta;
    private javax.swing.JLabel jLab_List_Cat_Venta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_List_Cat_Ventas;
    private javax.swing.JTextField jTxt_Cod_Cat_Venta;
    // End of variables declaration//GEN-END:variables
}
