package deprecated.vistas;

/**
 *
 * @author jav
 */
public class Confirmaciones extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    public Confirmaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Num_Ped_Conf = new javax.swing.JLabel();
        jLab_Rut_Cliente_Conf = new javax.swing.JLabel();
        jLab_Banco_Cliente_Conf = new javax.swing.JLabel();
        jTxt_Num_Ped_Conf = new javax.swing.JTextField();
        jTxt_Rut_Cliente_Conf = new javax.swing.JTextField();
        jLab_Nom_Cliente_Conf = new javax.swing.JLabel();
        jLab_Fec_Pago_Conf = new javax.swing.JLabel();
        jLab_Cod_Banco_Trans_Conf = new javax.swing.JLabel();
        jTxt_Nom_Cliente_Conf = new javax.swing.JTextField();
        jTxt_Fec_Pago_Conf = new javax.swing.JTextField();
        jTxt_Cod_Banco_Cliente_Conf = new javax.swing.JTextField();
        jBut_Cancel_Conf = new javax.swing.JButton();
        jBut_Conf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_List_Conf = new javax.swing.JTable();
        jComb_Banco_Cliente_Conf = new javax.swing.JComboBox<>();
        jBut_Sel_Conf = new javax.swing.JButton();
        jBut_Buscar_Conf = new javax.swing.JButton();
        jLab_List_Vent_Pend_pag = new javax.swing.JLabel();
        jLab_Conf_Pag_Client = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Num_Ped_Conf.setText("Número Pedido");
        getContentPane().add(jLab_Num_Ped_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 51, -1, -1));

        jLab_Rut_Cliente_Conf.setText("Rut");
        getContentPane().add(jLab_Rut_Cliente_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 97, -1, -1));

        jLab_Banco_Cliente_Conf.setText("Banco Cliente");
        getContentPane().add(jLab_Banco_Cliente_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 138, -1, -1));
        getContentPane().add(jTxt_Num_Ped_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 51, 136, -1));
        getContentPane().add(jTxt_Rut_Cliente_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 92, 136, -1));

        jLab_Nom_Cliente_Conf.setText("Nombre Cliente");
        getContentPane().add(jLab_Nom_Cliente_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 51, -1, -1));

        jLab_Fec_Pago_Conf.setText("Fecha Pago");
        getContentPane().add(jLab_Fec_Pago_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 95, -1, -1));

        jLab_Cod_Banco_Trans_Conf.setText("Código Transacción");
        getContentPane().add(jLab_Cod_Banco_Trans_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 136, -1, -1));
        getContentPane().add(jTxt_Nom_Cliente_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 51, 137, -1));
        getContentPane().add(jTxt_Fec_Pago_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 92, 137, -1));
        getContentPane().add(jTxt_Cod_Banco_Cliente_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 133, 137, -1));

        jBut_Cancel_Conf.setText("Cancelar");
        getContentPane().add(jBut_Cancel_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 175, -1, -1));

        jBut_Conf.setText("Confirmar");
        jBut_Conf.setToolTipText("");
        getContentPane().add(jBut_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 175, -1, -1));

        jTable_List_Conf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Número Pedido", "Nombre Cliente", "Rut", "Fecha Pedido", "Pack", "Teléfono", "Monto", "Selección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_List_Conf);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 295, 631, 159));

        jComb_Banco_Cliente_Conf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco Estado", "Banco Santander", "Itaú" }));
        getContentPane().add(jComb_Banco_Cliente_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 133, 136, -1));

        jBut_Sel_Conf.setText("Seleccionar");
        jBut_Sel_Conf.setToolTipText("");
        getContentPane().add(jBut_Sel_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 472, -1, -1));

        jBut_Buscar_Conf.setText("Buscar");
        getContentPane().add(jBut_Buscar_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jLab_List_Vent_Pend_pag.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLab_List_Vent_Pend_pag.setText("Ventas Pendiente de Pago");
        getContentPane().add(jLab_List_Vent_Pend_pag, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 241, -1, -1));

        jLab_Conf_Pag_Client.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLab_Conf_Pag_Client.setText("Confirma Pago Cliente");
        getContentPane().add(jLab_Conf_Pag_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirmaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirmaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirmaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirmaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirmaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Buscar_Conf;
    private javax.swing.JButton jBut_Cancel_Conf;
    private javax.swing.JButton jBut_Conf;
    private javax.swing.JButton jBut_Sel_Conf;
    private javax.swing.JComboBox<String> jComb_Banco_Cliente_Conf;
    private javax.swing.JLabel jLab_Banco_Cliente_Conf;
    private javax.swing.JLabel jLab_Cod_Banco_Trans_Conf;
    private javax.swing.JLabel jLab_Conf_Pag_Client;
    private javax.swing.JLabel jLab_Fec_Pago_Conf;
    private javax.swing.JLabel jLab_List_Vent_Pend_pag;
    private javax.swing.JLabel jLab_Nom_Cliente_Conf;
    private javax.swing.JLabel jLab_Num_Ped_Conf;
    private javax.swing.JLabel jLab_Rut_Cliente_Conf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_List_Conf;
    private javax.swing.JTextField jTxt_Cod_Banco_Cliente_Conf;
    private javax.swing.JTextField jTxt_Fec_Pago_Conf;
    private javax.swing.JTextField jTxt_Nom_Cliente_Conf;
    private javax.swing.JTextField jTxt_Num_Ped_Conf;
    private javax.swing.JTextField jTxt_Rut_Cliente_Conf;
    // End of variables declaration//GEN-END:variables
}
