package deprecated.vistas;

/**
 *
 * @author jav
 */
public class RRSS extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    public RRSS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Nom_RRSS = new javax.swing.JLabel();
        jLab_Cod_RRSS = new javax.swing.JLabel();
        jBut_Cancel_RRSS = new javax.swing.JButton();
        jBut_Guard_RRSS = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_List_RRSS = new javax.swing.JTable();
        jBut_Buscar_RRSS = new javax.swing.JButton();
        jTxt_Cod_RRSS = new javax.swing.JTextField();
        jComb_Nom_RRSS = new javax.swing.JComboBox<>();
        jBut_Ed_RRSS = new javax.swing.JButton();
        jBut_Des_RRSS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Nom_RRSS.setText("Nombre RRSS");
        getContentPane().add(jLab_Nom_RRSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, -1, -1));

        jLab_Cod_RRSS.setText("Código RRSS");
        getContentPane().add(jLab_Cod_RRSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 26, -1, -1));

        jBut_Cancel_RRSS.setText("Cancelar");
        getContentPane().add(jBut_Cancel_RRSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 99, -1, -1));

        jBut_Guard_RRSS.setText("Guardar");
        jBut_Guard_RRSS.setToolTipText("");
        getContentPane().add(jBut_Guard_RRSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 99, -1, -1));

        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 52, 22, -1));

        jTable_List_RRSS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre RRSS", "Código RRSS", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_List_RRSS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 152, 631, 159));

        jBut_Buscar_RRSS.setText("Buscar");
        getContentPane().add(jBut_Buscar_RRSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 99, -1, -1));
        getContentPane().add(jTxt_Cod_RRSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 23, 137, -1));

        jComb_Nom_RRSS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Whatsapp", "Facebook", "Instangram", "Teléfono" }));
        getContentPane().add(jComb_Nom_RRSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 23, 141, -1));

        jBut_Ed_RRSS.setText("Editar");
        getContentPane().add(jBut_Ed_RRSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 317, -1, -1));

        jBut_Des_RRSS.setText("Desactivar");
        jBut_Des_RRSS.setToolTipText("");
        getContentPane().add(jBut_Des_RRSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 317, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RRSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RRSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RRSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RRSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RRSS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Buscar_RRSS;
    private javax.swing.JButton jBut_Cancel_RRSS;
    private javax.swing.JButton jBut_Des_RRSS;
    private javax.swing.JButton jBut_Ed_RRSS;
    private javax.swing.JButton jBut_Guard_RRSS;
    private javax.swing.JComboBox<String> jComb_Nom_RRSS;
    private javax.swing.JLabel jLab_Cod_RRSS;
    private javax.swing.JLabel jLab_Nom_RRSS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_List_RRSS;
    private javax.swing.JTextField jTxt_Cod_RRSS;
    // End of variables declaration//GEN-END:variables
}
