/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author jav
 */
public class Artículos extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    public Artículos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Nom_Art = new javax.swing.JLabel();
        jLab_Unidades = new javax.swing.JLabel();
        jLab_Marca = new javax.swing.JLabel();
        jTxt_Nom_Art = new javax.swing.JTextField();
        jTxt_Unidades = new javax.swing.JTextField();
        jTxt_Marca = new javax.swing.JTextField();
        jLab_Cat_Art = new javax.swing.JLabel();
        jLab_F_V = new javax.swing.JLabel();
        jLab_Prov = new javax.swing.JLabel();
        jTxt_F_V = new javax.swing.JTextField();
        jBut_Cancel_Art = new javax.swing.JButton();
        jBut_Guard_Art = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_List_Art = new javax.swing.JTable();
        jBut_Buscar_Art = new javax.swing.JButton();
        jComb_Cat_Art = new javax.swing.JComboBox<>();
        jComb_Prov = new javax.swing.JComboBox<>();
        jLab_Cod_Art = new javax.swing.JLabel();
        jTxt_Cod_Art = new javax.swing.JTextField();
        jLab_List_Art = new javax.swing.JLabel();
        jBut_Ed_Art = new javax.swing.JButton();
        jBut_Des_Art = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Nom_Art.setText("Nombre Artículo");
        getContentPane().add(jLab_Nom_Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 26, -1, -1));

        jLab_Unidades.setText("Unidades");
        jLab_Unidades.setToolTipText("");
        getContentPane().add(jLab_Unidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 69, -1, -1));

        jLab_Marca.setText("Marca");
        getContentPane().add(jLab_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 110, -1, -1));
        getContentPane().add(jTxt_Nom_Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 23, 136, -1));
        getContentPane().add(jTxt_Unidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 66, 136, -1));
        getContentPane().add(jTxt_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 107, 136, -1));

        jLab_Cat_Art.setText("Categoría Artículo");
        getContentPane().add(jLab_Cat_Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 26, -1, -1));

        jLab_F_V.setText("Fecha de Vencimiento");
        getContentPane().add(jLab_F_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 69, -1, -1));

        jLab_Prov.setText("Proveedor");
        getContentPane().add(jLab_Prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 110, -1, -1));
        getContentPane().add(jTxt_F_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 66, 137, -1));

        jBut_Cancel_Art.setText("Cancelar");
        getContentPane().add(jBut_Cancel_Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 187, -1, -1));

        jBut_Guard_Art.setText("Guardar");
        jBut_Guard_Art.setToolTipText("");
        getContentPane().add(jBut_Guard_Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 187, -1, -1));

        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 300, 6, -1));

        jTable_List_Art.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre Artículo", "Categoría Artículo", "Unidades", "Fecha de Nacimiento", "Marca", "Proveedor", "Código Artículo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_List_Art);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 300, 631, 159));

        jBut_Buscar_Art.setText("Buscar");
        getContentPane().add(jBut_Buscar_Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 187, -1, -1));
        getContentPane().add(jComb_Cat_Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 23, 137, -1));

        jComb_Prov.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComb_Prov.setToolTipText("");
        getContentPane().add(jComb_Prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 107, 137, -1));

        jLab_Cod_Art.setText("Código Artículo");
        getContentPane().add(jLab_Cod_Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 149, -1, -1));
        getContentPane().add(jTxt_Cod_Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 146, 136, -1));

        jLab_List_Art.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLab_List_Art.setText("Artículos");
        getContentPane().add(jLab_List_Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 254, -1, -1));

        jBut_Ed_Art.setText("Editar");
        getContentPane().add(jBut_Ed_Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 465, -1, -1));

        jBut_Des_Art.setText("Desactivar");
        jBut_Des_Art.setToolTipText("");
        getContentPane().add(jBut_Des_Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 465, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Artículos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Artículos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Artículos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Artículos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Artículos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Buscar_Art;
    private javax.swing.JButton jBut_Cancel_Art;
    private javax.swing.JButton jBut_Des_Art;
    private javax.swing.JButton jBut_Ed_Art;
    private javax.swing.JButton jBut_Guard_Art;
    private javax.swing.JComboBox<String> jComb_Cat_Art;
    private javax.swing.JComboBox<String> jComb_Prov;
    private javax.swing.JLabel jLab_Cat_Art;
    private javax.swing.JLabel jLab_Cod_Art;
    private javax.swing.JLabel jLab_F_V;
    private javax.swing.JLabel jLab_List_Art;
    private javax.swing.JLabel jLab_Marca;
    private javax.swing.JLabel jLab_Nom_Art;
    private javax.swing.JLabel jLab_Prov;
    private javax.swing.JLabel jLab_Unidades;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_List_Art;
    private javax.swing.JTextField jTxt_Cod_Art;
    private javax.swing.JTextField jTxt_F_V;
    private javax.swing.JTextField jTxt_Marca;
    private javax.swing.JTextField jTxt_Nom_Art;
    private javax.swing.JTextField jTxt_Unidades;
    // End of variables declaration//GEN-END:variables
}
