package vista;

/**
 *
 * @author jav
 */
public class Bancos extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    public Bancos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLab_Banco = new javax.swing.JLabel();
        jBut_Cancel_Bancos = new javax.swing.JButton();
        jBut_Guard_Bancos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_List_Bancos = new javax.swing.JTable();
        jBut_Buscar_Bancos = new javax.swing.JButton();
        jLab_List_Bancos = new javax.swing.JLabel();
        jBut_Ed_Bancos = new javax.swing.JButton();
        jBut_Des_Bancos = new javax.swing.JButton();
        txtBanco = new javax.swing.JTextField();

        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Banco.setText("Banco");
        jLab_Banco.setAutoscrolls(true);
        getContentPane().add(jLab_Banco, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jBut_Cancel_Bancos.setText("Cancelar");
        jBut_Cancel_Bancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_Cancel_BancosActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_Cancel_Bancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 99, -1, -1));

        jBut_Guard_Bancos.setText("Guardar");
        jBut_Guard_Bancos.setToolTipText("");
        getContentPane().add(jBut_Guard_Bancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 99, -1, -1));

        jTable_List_Bancos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código Banco", "Banco", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_List_Bancos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 198, 631, 159));

        jBut_Buscar_Bancos.setText("Buscar");
        getContentPane().add(jBut_Buscar_Bancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 99, -1, -1));

        jLab_List_Bancos.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLab_List_Bancos.setText("Bancos");
        getContentPane().add(jLab_List_Bancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 152, -1, -1));

        jBut_Ed_Bancos.setText("Editar");
        jBut_Ed_Bancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_Ed_BancosActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_Ed_Bancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 375, -1, -1));

        jBut_Des_Bancos.setText("Desactivar");
        jBut_Des_Bancos.setToolTipText("");
        getContentPane().add(jBut_Des_Bancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 375, -1, -1));
        getContentPane().add(txtBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_Cancel_BancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_Cancel_BancosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBut_Cancel_BancosActionPerformed

    private void jBut_Ed_BancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_Ed_BancosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBut_Ed_BancosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bancos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Buscar_Bancos;
    private javax.swing.JButton jBut_Cancel_Bancos;
    private javax.swing.JButton jBut_Des_Bancos;
    private javax.swing.JButton jBut_Ed_Bancos;
    private javax.swing.JButton jBut_Guard_Bancos;
    private javax.swing.JLabel jLab_Banco;
    private javax.swing.JLabel jLab_List_Bancos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_List_Bancos;
    private javax.swing.JTextField txtBanco;
    // End of variables declaration//GEN-END:variables
}
