/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.Login to edit this template
 */
package Vista;

/**
 *
 * @author jav
 */
public class Categoria_Pack extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    public Categoria_Pack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Cat_Pack = new javax.swing.JLabel();
        jLab_Cod_Cat_Pack = new javax.swing.JLabel();
        jBut_Cancel_Cat_Pack = new javax.swing.JButton();
        jBut_Guard_Cat_Pack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_List_Cat_Pack = new javax.swing.JTable();
        jBut_Buscar_Cat_Pack = new javax.swing.JButton();
        jLab_Est_Cat_Pack = new javax.swing.JLabel();
        jComb_Est_Cat_Pack = new javax.swing.JComboBox<>();
        jTxt_Cod_Cat_Pack = new javax.swing.JTextField();
        jComb_Cat_Pack = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Cat_Pack.setText("Categoría Pack");
        getContentPane().add(jLab_Cat_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, -1, -1));

        jLab_Cod_Cat_Pack.setText("Código Categoría Pack");
        getContentPane().add(jLab_Cod_Cat_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 26, -1, -1));

        jBut_Cancel_Cat_Pack.setText("Eliminar");
        getContentPane().add(jBut_Cancel_Cat_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 99, -1, -1));

        jBut_Guard_Cat_Pack.setText("Guardar/Actualizar");
        jBut_Guard_Cat_Pack.setToolTipText("");
        getContentPane().add(jBut_Guard_Cat_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 99, -1, -1));

        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 52, 22, -1));

        jTable_List_Cat_Pack.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código Categoría Pack", "Categoría Pack", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                Login.lang.String.class, Login.lang.String.class, Login.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_List_Cat_Pack);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 152, 631, 159));

        jBut_Buscar_Cat_Pack.setText("Buscar");
        getContentPane().add(jBut_Buscar_Cat_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 99, -1, -1));

        jLab_Est_Cat_Pack.setText("Estado");
        jLab_Est_Cat_Pack.setToolTipText("");
        getContentPane().add(jLab_Est_Cat_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, -1, -1));

        jComb_Est_Cat_Pack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activado", "Desactivado" }));
        getContentPane().add(jComb_Est_Cat_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 58, 141, -1));
        getContentPane().add(jTxt_Cod_Cat_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 23, 137, -1));

        jComb_Cat_Pack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cumpleaños", "Día de Enamorados", "Aniversarios‌‌ de‌‌ pololos‌ ‌", "Día‌‌ de‌‌ novios‌ ‌", "Matrimonios‌‌ o‌‌ citas‌‌ románticas‌ ‌", "Desayunos‌ ‌" }));
        getContentPane().add(jComb_Cat_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 23, 141, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Login.util.logging.Logger.getLogger(Categoria_Pack.class.getName()).log(Login.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Login.util.logging.Logger.getLogger(Categoria_Pack.class.getName()).log(Login.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Login.util.logging.Logger.getLogger(Categoria_Pack.class.getName()).log(Login.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Login.util.logging.Logger.getLogger(Categoria_Pack.class.getName()).log(Login.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        Login.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categoria_Pack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Buscar_Cat_Pack;
    private javax.swing.JButton jBut_Cancel_Cat_Pack;
    private javax.swing.JButton jBut_Guard_Cat_Pack;
    private javax.swing.JComboBox<String> jComb_Cat_Pack;
    private javax.swing.JComboBox<String> jComb_Est_Cat_Pack;
    private javax.swing.JLabel jLab_Cat_Pack;
    private javax.swing.JLabel jLab_Cod_Cat_Pack;
    private javax.swing.JLabel jLab_Est_Cat_Pack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_List_Cat_Pack;
    private javax.swing.JTextField jTxt_Cod_Cat_Pack;
    // End of variables declaration//GEN-END:variables
}
