package Vista;

/**
 *
 * @author jav
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Nom_Cliente = new javax.swing.JLabel();
        jLab_Telf = new javax.swing.JLabel();
        jLab_email = new javax.swing.JLabel();
        jLab_RRSS = new javax.swing.JLabel();
        jTxt_N_C = new javax.swing.JTextField();
        jTxt_Telf = new javax.swing.JTextField();
        jTxt_email = new javax.swing.JTextField();
        jLab_Rut = new javax.swing.JLabel();
        jLab_F_N = new javax.swing.JLabel();
        jLab_Cel = new javax.swing.JLabel();
        jTxt_Rut = new javax.swing.JTextField();
        jTxt_F_N = new javax.swing.JTextField();
        jTxt_Cel = new javax.swing.JTextField();
        jBut_Cancel_Client = new javax.swing.JButton();
        jBut_Guard_Client = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_List_Cliente = new javax.swing.JTable();
        jComb_RRSS = new javax.swing.JComboBox<>();
        jBut_Buscar = new javax.swing.JButton();
        jBut_Venta = new javax.swing.JButton();
        jLab_List_Client = new javax.swing.JLabel();
        jBut_Edit_Client = new javax.swing.JButton();
        jBut_Des_Client = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Nom_Cliente.setText("Nombre Cliente");
        getContentPane().add(jLab_Nom_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 20, -1, -1));

        jLab_Telf.setText("Teléfono");
        getContentPane().add(jLab_Telf, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 55, -1, -1));

        jLab_email.setText("Email");
        getContentPane().add(jLab_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 90, -1, -1));

        jLab_RRSS.setText("RRSS");
        getContentPane().add(jLab_RRSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 125, -1, -1));
        getContentPane().add(jTxt_N_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 17, 136, -1));
        getContentPane().add(jTxt_Telf, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 52, 136, -1));
        getContentPane().add(jTxt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 87, 136, -1));

        jLab_Rut.setText("Rut");
        getContentPane().add(jLab_Rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 20, -1, -1));

        jLab_F_N.setText("Fecha de Nacimiento");
        getContentPane().add(jLab_F_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 55, -1, -1));

        jLab_Cel.setText("Celular");
        getContentPane().add(jLab_Cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 90, -1, -1));
        getContentPane().add(jTxt_Rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 17, 137, -1));
        getContentPane().add(jTxt_F_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 52, 137, -1));
        getContentPane().add(jTxt_Cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 87, 137, -1));

        jBut_Cancel_Client.setText("Cancelar");
        getContentPane().add(jBut_Cancel_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 192, -1, -1));

        jBut_Guard_Client.setText("Guardar");
        jBut_Guard_Client.setToolTipText("");
        getContentPane().add(jBut_Guard_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 192, -1, -1));

        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 233, 0, -1));

        jTable_List_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre Cliente", "Rut", "Email", "Celular", "Teléfono", "RRSS", "Fecha de Nacimiento", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_List_Cliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 331, 631, 159));

        jComb_RRSS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Whatsapp", "Telefono", "Facebook", "Instangram" }));
        getContentPane().add(jComb_RRSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 122, 136, -1));

        jBut_Buscar.setText("Buscar");
        getContentPane().add(jBut_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 192, -1, -1));

        jBut_Venta.setText("Venta");
        jBut_Venta.setToolTipText("");
        getContentPane().add(jBut_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 508, -1, -1));

        jLab_List_Client.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLab_List_Client.setText("Lista de Clientes");
        getContentPane().add(jLab_List_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 262, -1, -1));

        jBut_Edit_Client.setText("Editar");
        getContentPane().add(jBut_Edit_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 508, -1, -1));

        jBut_Des_Client.setText("Desactivar");
        jBut_Des_Client.setToolTipText("");
        getContentPane().add(jBut_Des_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 508, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Buscar;
    private javax.swing.JButton jBut_Cancel_Client;
    private javax.swing.JButton jBut_Des_Client;
    private javax.swing.JButton jBut_Edit_Client;
    private javax.swing.JButton jBut_Guard_Client;
    private javax.swing.JButton jBut_Venta;
    private javax.swing.JComboBox<String> jComb_RRSS;
    private javax.swing.JLabel jLab_Cel;
    private javax.swing.JLabel jLab_F_N;
    private javax.swing.JLabel jLab_List_Client;
    private javax.swing.JLabel jLab_Nom_Cliente;
    private javax.swing.JLabel jLab_RRSS;
    private javax.swing.JLabel jLab_Rut;
    private javax.swing.JLabel jLab_Telf;
    private javax.swing.JLabel jLab_email;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_List_Cliente;
    private javax.swing.JTextField jTxt_Cel;
    private javax.swing.JTextField jTxt_F_N;
    private javax.swing.JTextField jTxt_N_C;
    private javax.swing.JTextField jTxt_Rut;
    private javax.swing.JTextField jTxt_Telf;
    private javax.swing.JTextField jTxt_email;
    // End of variables declaration//GEN-END:variables
}
