package vista;

/**
 *
 * @author jav
 */
public class Informes_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    public Informes_Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_F_Ini_Inf_Cliente = new javax.swing.JLabel();
        jLab_Busc_Rut_Inf_Client = new javax.swing.JLabel();
        jTxt_F_Ini_Inf_Client = new javax.swing.JTextField();
        jLab_F_Fin_Inf_Client = new javax.swing.JLabel();
        jTxt_Busc_Rut_Inf_Client = new javax.swing.JTextField();
        jBut_Busc_Rut_Inf_Client = new javax.swing.JButton();
        jBut_Desc_Inf_Client = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Det_Vent_Inf_Client = new javax.swing.JTable();
        jLab_Det_Vent_Inf_Client = new javax.swing.JLabel();
        jTxt_F_Fin_Inf_Client1 = new javax.swing.JTextField();
        jLab_Busq_Inf_Ventas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_F_Ini_Inf_Cliente.setText("Desde");
        getContentPane().add(jLab_F_Ini_Inf_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, -1, -1));

        jLab_Busc_Rut_Inf_Client.setText("Búsqueda Rut");
        jLab_Busc_Rut_Inf_Client.setToolTipText("");
        getContentPane().add(jLab_Busc_Rut_Inf_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 59, -1, -1));
        getContentPane().add(jTxt_F_Ini_Inf_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 56, 136, -1));

        jLab_F_Fin_Inf_Client.setText("Hasta");
        getContentPane().add(jLab_F_Fin_Inf_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 94, -1, -1));
        getContentPane().add(jTxt_Busc_Rut_Inf_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 56, 137, -1));

        jBut_Busc_Rut_Inf_Client.setText("Buscar");
        getContentPane().add(jBut_Busc_Rut_Inf_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 128, -1, -1));

        jBut_Desc_Inf_Client.setText("Descargar");
        getContentPane().add(jBut_Desc_Inf_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 412, -1, -1));

        jTable_Det_Vent_Inf_Client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código Pack", "Pack", "Fecha Registro", "Cliente", "Estado", "Comuna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_Det_Vent_Inf_Client);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 247, 631, 159));

        jLab_Det_Vent_Inf_Client.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLab_Det_Vent_Inf_Client.setText("Detalle de Ventas Realizadas");
        jLab_Det_Vent_Inf_Client.setToolTipText("");
        getContentPane().add(jLab_Det_Vent_Inf_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 201, -1, -1));

        jTxt_F_Fin_Inf_Client1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_F_Fin_Inf_Client1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTxt_F_Fin_Inf_Client1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 91, 137, -1));

        jLab_Busq_Inf_Ventas.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLab_Busq_Inf_Ventas.setText("Búsqueda de Ventas");
        getContentPane().add(jLab_Busq_Inf_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_F_Fin_Inf_Client1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_F_Fin_Inf_Client1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_F_Fin_Inf_Client1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informes_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informes_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informes_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informes_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informes_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Busc_Rut_Inf_Client;
    private javax.swing.JButton jBut_Desc_Inf_Client;
    private javax.swing.JLabel jLab_Busc_Rut_Inf_Client;
    javax.swing.JLabel jLab_Busq_Inf_Ventas;
    private javax.swing.JLabel jLab_Det_Vent_Inf_Client;
    private javax.swing.JLabel jLab_F_Fin_Inf_Client;
    private javax.swing.JLabel jLab_F_Ini_Inf_Cliente;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_Det_Vent_Inf_Client;
    private javax.swing.JTextField jTxt_Busc_Rut_Inf_Client;
    private javax.swing.JTextField jTxt_F_Fin_Inf_Client1;
    private javax.swing.JTextField jTxt_F_Ini_Inf_Client;
    // End of variables declaration//GEN-END:variables
}
