/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.Login to edit this template
 */
package Vista;

/**
 *
 * @author jav
 */
public class Packs extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    public Packs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Nom_Packs = new javax.swing.JLabel();
        jLab_Pack = new javax.swing.JLabel();
        jTxt_Nom_Pack = new javax.swing.JTextField();
        jTxt_Unid_Pack = new javax.swing.JTextField();
        jLab_Prec_Pack = new javax.swing.JLabel();
        jBut_Cancel_Pack = new javax.swing.JButton();
        jBut_Guard_Pack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_List_Pack = new javax.swing.JTable();
        jBut_Buscar_Pack = new javax.swing.JButton();
        jTxt_Prec_Pack = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_Pack = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTxt_Pack = new javax.swing.JTextArea();
        jBut_add_Art_Pack = new javax.swing.JButton();
        jBut_sust_Art_Pack = new javax.swing.JButton();
        jLab_List_Pack = new javax.swing.JLabel();
        jBut_Ed_Pack = new javax.swing.JButton();
        jBut_Des_Pack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Nom_Packs.setText("Nombre Packs");
        getContentPane().add(jLab_Nom_Packs, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, -1, -1));

        jLab_Pack.setText("Unidades");
        jLab_Pack.setToolTipText("");
        getContentPane().add(jLab_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 109, -1, -1));
        getContentPane().add(jTxt_Nom_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 23, 136, -1));

        jTxt_Unid_Pack.addActionListener(new Login.awt.event.ActionListener() {
            public void actionPerformed(Login.awt.event.ActionEvent evt) {
                jTxt_Unid_PackActionPerformed(evt);
            }
        });
        getContentPane().add(jTxt_Unid_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 106, -1, -1));

        jLab_Prec_Pack.setText("Precio Pack");
        getContentPane().add(jLab_Prec_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 26, -1, -1));

        jBut_Cancel_Pack.setText("Cancelar");
        getContentPane().add(jBut_Cancel_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 208, -1, -1));

        jBut_Guard_Pack.setText("Guardar");
        jBut_Guard_Pack.setToolTipText("");
        getContentPane().add(jBut_Guard_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 208, -1, -1));

        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 249, 22, -1));

        jTable_List_Pack.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código Pack", "Nombre Pack", "Unidades Bodega", "Precio Pack", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                Login.lang.String.class, Login.lang.String.class, Login.lang.Integer.class, Login.lang.Integer.class, Login.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_List_Pack);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 307, 631, 159));

        jBut_Buscar_Pack.setText("Buscar");
        getContentPane().add(jBut_Buscar_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 208, -1, -1));
        getContentPane().add(jTxt_Prec_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 23, 137, -1));

        jList_Pack.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList_Pack);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, 164, 115));

        jTxt_Pack.setColumns(20);
        jTxt_Pack.setRows(5);
        jScrollPane4.setViewportView(jTxt_Pack);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 71, 221, 119));

        jBut_add_Art_Pack.setText(">");
        jBut_add_Art_Pack.addActionListener(new Login.awt.event.ActionListener() {
            public void actionPerformed(Login.awt.event.ActionEvent evt) {
                jBut_add_Art_PackActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_add_Art_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 62, -1, -1));

        jBut_sust_Art_Pack.setText("<");
        getContentPane().add(jBut_sust_Art_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 141, -1, -1));

        jLab_List_Pack.setFont(new Login.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLab_List_Pack.setText("Tabla Packs");
        getContentPane().add(jLab_List_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 261, -1, -1));

        jBut_Ed_Pack.setText("Editar");
        getContentPane().add(jBut_Ed_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 472, -1, -1));

        jBut_Des_Pack.setText("Desactivar");
        jBut_Des_Pack.setToolTipText("");
        getContentPane().add(jBut_Des_Pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 472, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_add_Art_PackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_add_Art_PackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBut_add_Art_PackActionPerformed

    private void jTxt_Unid_PackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_Unid_PackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_Unid_PackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Login.util.logging.Logger.getLogger(Packs.class.getName()).log(Login.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Login.util.logging.Logger.getLogger(Packs.class.getName()).log(Login.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Login.util.logging.Logger.getLogger(Packs.class.getName()).log(Login.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Login.util.logging.Logger.getLogger(Packs.class.getName()).log(Login.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        Login.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Packs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Buscar_Pack;
    private javax.swing.JButton jBut_Cancel_Pack;
    private javax.swing.JButton jBut_Des_Pack;
    private javax.swing.JButton jBut_Ed_Pack;
    private javax.swing.JButton jBut_Guard_Pack;
    private javax.swing.JButton jBut_add_Art_Pack;
    private javax.swing.JButton jBut_sust_Art_Pack;
    private javax.swing.JLabel jLab_List_Pack;
    private javax.swing.JLabel jLab_Nom_Packs;
    private javax.swing.JLabel jLab_Pack;
    private javax.swing.JLabel jLab_Prec_Pack;
    private javax.swing.JList<String> jList_Pack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_List_Pack;
    private javax.swing.JTextField jTxt_Nom_Pack;
    private javax.swing.JTextArea jTxt_Pack;
    private javax.swing.JTextField jTxt_Prec_Pack;
    private javax.swing.JTextField jTxt_Unid_Pack;
    // End of variables declaration//GEN-END:variables
}
